name: halal_scan
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.0.5
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_auth: ^4.0.1
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.7
  flutter_share: ^2.0.0
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_sign_in: ^5.4.2
  image_viewer: ^1.5.0
  intl: ^0.17.0
  ionicons: ^0.2.1
  lottie: ^2.0.0
  material_color_generator: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.14.0
  provider: ^6.0.4
  qr_code_scanner: ^1.0.1
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  timeago: ^3.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
