name: halal_scan
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.11.2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  ionicons: ^0.2.1
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
