name: halal_scan
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  ionicons: ^0.2.1
  mobile_scanner: ^2.0.0
  outline_search_bar: ^2.3.0
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.4
  timeago: ^3.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
