// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_eQCr4tnHys4Pmg6B3oA9zoXxP09KIIk',
    appId: '1:957559533289:android:9a29c760b0570e6b9c8a78',
    messagingSenderId: '957559533289',
    projectId: 'halal-scan-91706',
    storageBucket: 'halal-scan-91706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkzTTjWJqBfkS8_GqBmbT5ZkMxyomKvgg',
    appId: '1:957559533289:ios:331e01d3ea0d3c389c8a78',
    messagingSenderId: '957559533289',
    projectId: 'halal-scan-91706',
    storageBucket: 'halal-scan-91706.appspot.com',
    iosClientId:
        '957559533289-6181eldm3bsg7u05m3gjcvda2j254cvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.halalScan',
  );
}
